import dayjs from 'dayjs';
import { ClassType } from '../Calendar/constants';
import 'dayjs/locale/zh-tw';

dayjs.locale('zh-TW');

export const mockData = [
  {
    title: dayjs('2023/04/09').format('MM/DD（dd）'),
    classes: [
      {
        from: '2023/04/09 09:00',
        to: '2023/04/09 10:00',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻', '甘丞旻', '石丞旻', '白丞旻'],
        type: ClassType.PersonalOneToMany,
        gift: true,
        deducted: false,
        expired: false,
      },
      {
        from: '2023/04/09 10:00',
        to: '2023/04/09 11:30',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻', '甘丞旻', '石丞旻', '白丞旻'],
        type: ClassType.PersonalOneToMany,
        gift: true,
        deducted: true,
        expired: false,
      },
      {
        from: '2023/04/09 11:30',
        to: '2023/04/09 13:00',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻'],
        type: ClassType.PersonalOneToMany,
        gift: true,
        deducted: false,
        expired: true,
      },
      {
        from: '2023/04/09 14:00',
        to: '2023/04/09 18:30',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻'],
        type: ClassType.Group,
        gift: false,
        deducted: false,
        expired: false,
      },
    ],
  },
  {
    title: dayjs('2023/04/10').format('MM/DD（dd）'),
    classes: [
      {
        from: '2023/04/10 09:00',
        to: '2023/04/10 10:00',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻', '甘丞旻', '石丞旻', '白丞旻'],
        type: ClassType.PersonalOneToMany,
        gift: false,
        deducted: false,
        expired: false,
      },
      {
        from: '2023/04/10 10:00',
        to: '2023/04/10 11:30',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻', '甘丞旻', '石丞旻', '白丞旻'],
        type: ClassType.PersonalOneToMany,
        gift: false,
        deducted: true,
        expired: false,
      },
      {
        from: '2023/04/10 11:30',
        to: '2023/04/10 13:00',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻'],
        type: ClassType.PersonalOneToMany,
        gift: false,
        deducted: false,
        expired: true,
      },
      {
        from: '2023/04/10 14:00',
        to: '2023/04/10 18:30',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻'],
        type: ClassType.Group,
        gift: false,
        deducted: false,
        expired: false,
      },
    ],
  },
  {
    title: dayjs('2023/04/11').format('MM/DD（dd）'),
    classes: [
      {
        from: '2023/04/11 09:00',
        to: '2023/04/11 10:00',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻'],
        type: ClassType.PersonalOneToOne,
        gift: false,
        deducted: false,
        expired: false,
      },
      {
        from: '2023/04/11 10:00',
        to: '2023/04/11 11:30',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['黃丞旻'],
        type: ClassType.PersonalOneToOne,
        gift: true,
        deducted: true,
        expired: false,
      },
      {
        from: '2023/04/11 11:30',
        to: '2023/04/11 13:00',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['王丞旻'],
        type: ClassType.PersonalOneToOne,
        gift: true,
        deducted: false,
        expired: false,
      },
      {
        from: '2023/04/11 14:00',
        to: '2023/04/11 18:30',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻'],
        type: ClassType.Group,
        gift: false,
        deducted: false,
        expired: false,
      },
    ],
  },
  {
    title: dayjs('2023/04/12').format('MM/DD（dd）'),
    classes: [
      {
        from: '2023/04/12 09:00',
        to: '2023/04/12 10:00',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻'],
        type: ClassType.Group,
        gift: false,
        deducted: false,
        expired: false,
      },
      {
        from: '2023/04/12 10:00',
        to: '2023/04/12 11:30',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻'],
        type: ClassType.Group,
        gift: false,
        deducted: true,
        expired: false,
      },
      {
        from: '2023/04/12 11:30',
        to: '2023/04/12 13:00',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻'],
        type: ClassType.Group,
        gift: false,
        deducted: false,
        expired: false,
      },
      {
        from: '2023/04/12 14:00',
        to: '2023/04/12 18:30',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻'],
        type: ClassType.Group,
        gift: false,
        deducted: false,
        expired: false,
      },
    ],
  },
  {
    title: dayjs('2023/04/13').format('MM/DD（dd）'),
    classes: [
      {
        from: '2023/04/13 09:00',
        to: '2023/04/13 10:00',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻'],
        type: ClassType.Group,
        gift: false,
        deducted: false,
        expired: false,
      },
      {
        from: '2023/04/13 10:00',
        to: '2023/04/13 11:30',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻'],
        type: ClassType.Group,
        gift: false,
        deducted: true,
        expired: false,
      },
      {
        from: '2023/04/13 11:30',
        to: '2023/04/13 13:00',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻'],
        type: ClassType.Group,
        gift: false,
        deducted: false,
        expired: false,
      },
      {
        from: '2023/04/13 14:00',
        to: '2023/04/13 18:00',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻'],
        type: ClassType.Group,
        gift: false,
        deducted: false,
        expired: false,
      },
    ],
  },
  {
    title: dayjs('2023/04/14').format('MM/DD（dd）'),
    classes: [
      {
        from: '2023/04/14 09:00',
        to: '2023/04/14 10:00',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻'],
        type: ClassType.Group,
        gift: false,
        deducted: false,
        expired: false,
      },
      {
        from: '2023/04/14 10:00',
        to: '2023/04/14 11:30',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻'],
        type: ClassType.Group,
        gift: false,
        deducted: true,
        expired: false,
      },
      {
        from: '2023/04/14 11:30',
        to: '2023/04/14 13:00',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻'],
        type: ClassType.Group,
        gift: false,
        deducted: false,
        expired: false,
      },
      {
        from: '2023/04/14 14:00',
        to: '2023/04/14 18:30',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻'],
        type: ClassType.Group,
        gift: false,
        deducted: false,
        expired: false,
      },
    ],
  },
  {
    title: dayjs('2023/04/15').format('MM/DD（dd）'),
    classes: [
      {
        from: '2023/04/15 08:30',
        to: '2023/04/15 10:00',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻'],
        type: ClassType.Consultation,
        gift: false,
        deducted: false,
        expired: false,
      },
      {
        from: '2023/04/15 10:00',
        to: '2023/04/15 11:30',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻'],
        type: ClassType.Group,
        gift: false,
        deducted: true,
        expired: false,
      },
      {
        from: '2023/04/15 12:00',
        to: '2023/04/15 13:00',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻', '甘丞旻', '石丞旻'],
        type: ClassType.Group,
        gift: false,
        deducted: false,
        expired: false,
      },
      {
        from: '2023/04/15 14:05',
        to: '2023/04/15 15:05',
        name: 'TRX 中階訓練',
        coach: '王思敏',
        students: ['丁丞旻', '王丞旻', '黃丞旻', '甘丞旻', '石丞旻', '白丞旻'],
        type: ClassType.Group,
        gift: false,
        deducted: true,
        expired: false,
      },
    ],
  },
];
